apiVersion: v1
data:
    token: ZXlKaElqb2lNbU5oTkRGaFptWmxPVE5sT1dZd09XWTNNVFkzWVRFMllqbGxNRFE1WldVaUxDSjBJam9pTnprd1pEUXhNVEl0WVRjeE1TMDBOVGMyTFRsaE5qVXRPV016T0RsbFptTXpOR014SWl3aWN5STZJazVxVW1sTmFsWnFXVzFSZEUxSFZYZFBRekF3VDBScmVFeFVhM2haYlZWMFdWZEpNRTFIVm1sYWFrbDNXbFJKTlNKOQ==
kind: Secret
metadata:
    name: tunnel-token
    namespace: cloudflared
type: Opaque